# Generated by Django 4.1.6 on 2023-09-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_alter_post_author_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Sohan Awesome Blog', max_length=300),
        ),
    ]
